# -------------------------------------------------------------------------------------------------
# ExpugnExtras Configuration File
# -------------------------------------------------------------------------------------------------
# Warning: Modify this config with caution. Altering some values could break the plugin.
#          Only modify this config if you know what you're doing.
# -------------------------------------------------------------------------------------------------
# expugn: Determines if '/expugn' is enabled or not. Entire plugin must be reset for this to take effect.
# marriage: Determines if '/marriage' is enabled or not. Entire plugin must be reset for this to take effect.
# -------------------------------------------------------------------------------------------------
expugn: true