name: ExpugnExtras
main: io.github.expugn.ExpugnExtras
version: ${version}
commands:
	expugn:
		description: Alias for ExpugnExtras.
		usage: /expugn [parameter]
		permission: expugnextras.admin
		permission-message: You do not have <permission>.