name: ExpugnExtras
version: 5.0
description: 'A plugin with miscellaneous features.'

author: Expugn
website: https://github.com/Expugn/ExpugnExtras

main: io.github.expugn.expugnextras.ExpugnExtras
database: false
depend: [Titles, PermissionsEx]
softdepend: [VariableTriggers, Vault]

commands:
  expugn:
    description: Alias for ExpugnExtras.
    usage: '/expugn [parameter]'
  titles:
    description: Link from /expugn listtitles.
    usage: '/titles <page #>'