name: ExpugnExtras
version: 4.0
description: 'A plugin with miscellaneous features.'

author: Expugn
website: https://github.com/Expugn/ExpugnExtras

main: io.github.expugn.expugnextras.ExpugnExtras
database: false
depend: [TitleManager, PermissionsEx]
softdepend: [VariableTriggers, Vault]

commands:
  expugn:
    description: Alias for ExpugnExtras.
    usage: '/expugn [parameter]'
  marriage:
    description: Alias for Marriage.
    usage: '/marriage [parameter]'