name: ExpugnExtras
version: 3.4.2
description: 'A plugin with miscellaneous features.'

author: Expugn
website: https://github.com/Expugn/ExpugnExtras

main: io.github.expugn.expugnextras.ExpugnExtras
database: false
depend: [TitleManager, PermissionsEx]
softdepend: [VariableTriggers, Vault]

commands:
  expugn:
    description: Alias for ExpugnExtras.
    usage: '/expugn [parameter]'
    permission: expugnextras.admin
    permission-message: 'You do not have <permission>.'
  marriage:
    description: Alias for Marriage.
    usage: '/marriage [parameter]'
  expugnfree:
    description: Alias for ExpugnFree.
    usage: '/expugnfree [parameter]'
  expugnconsole:
    description: Alias for ExpugnConsole.
    usage: '/expugnconsole [parameter]'
    permission: expugnextras.admin
    permission-message: 'You do not have <permission>'
  gollem:
    description: Alias for Gollem.
    uasge: '/gollem [parameter]'
    permission: expugnextras.admin
    permission-message: 'You do not have <permission>'